## Imports & Setup

In [2]:
# Standard libraries
import pandas as pd
import numpy as np
import re
import string

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

## Load Dataset

In [3]:
# Load raw dataset
df = pd.read_csv("../data/raw/job_postings.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1615940, 23)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,2022-04-24,Female,Brandon Cunningham,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagem...","{'Flexible Spending Accounts (FSAs), Relocation Assistance, Legal Assistance, Employee Recognition Programs, Financial Counseling'}","Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising","Manage and grow social media accounts, create engaging content, and interact with the online community. Develop social media content calendars and strategies. Monitor social media trends and engag...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversified Financials"",""City"":""Sunny Isles Beach"",""State"":""Florida"",""Zip"":""33160"",""Website"":""www.ielp.com"",""Ticker"":""IEP"",""CEO"":""David Willetts""}"
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,2022-12-19,Female,Francisco Larsen,461-509-4216,Web Developer,Frontend Web Developer,Idealist,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create ...","{'Health Insurance, Retirement Plans, Paid Time Off (PTO), Flexible Work Arrangements, Employee Assistance Programs (EAP)'}","HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)","Design and code user interfaces for websites, ensuring a seamless and visually appealing user experience. Collaborate with UX designers to optimize user journeys. Ensure cross-browser compatibilit...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Commercial Banks"",""City"":""Pittsburgh"",""State"":""Pennsylvania"",""Zip"":""15222"",""Website"":""www.pnc.com"",""Ticker"":""PNC"",""CEO"":""William S. Demchak""}"
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,2022-09-14,Male,Gary Gibson,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain p...","{'Legal Assistance, Bonuses and Incentive Programs, Wellness Programs, Employee Discounts, Retirement Plans'}","Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge",Establish and enforce quality control standards and procedures. Conduct quality audits and inspections. Collaborate with production teams to address quality issues and implement improvements.,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: Property and Casualty (Stock)"",""City"":""San Antonio"",""State"":""Texas"",""Zip"":""78288"",""Website"":""www.usaa.com"",""Ticker"":"""",""CEO"":""Wayne Peacock""}"
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,2023-02-25,Female,Joy Lucero,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, and maintain wireless network solutions. They optimize wireless connectivity, troubleshoot issues, and ensure reliable and secure wireless communicati...","{'Transportation Benefits, Professional Development, Bonuses and Incentive Programs, Profit-Sharing, Employee Discounts'}",Wireless network design and architecture Wi-Fi standards and protocols RF (Radio Frequency) planning and optimization Wireless security protocols Troubleshooting wireless network issues,"Design, configure, and optimize wireless networks, ensuring reliable and secure wireless connectivity. Troubleshoot wireless network issues. Plan and implement wireless network upgrades.",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-Oil Production"",""City"":""New York"",""State"":""New York"",""Zip"":""10036"",""Website"":""www.hess.com"",""Ticker"":""HES"",""CEO"":""John B. Hess""}"
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,2022-10-11,Female,Julie Johnson,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,"A Conference Manager coordinates and manages conferences, meetings, and events. They plan logistics, handle budgeting, liaise with vendors, and ensure the smooth execution of events, catering to t...","{'Flexible Spending Accounts (FSAs), Relocation Assistance, Legal Assistance, Employee Recognition Programs, Financial Counseling'}",Event planning Conference logistics Budget management Vendor coordination Marketing and promotion Client relations,"Specialize in conference and convention planning. Coordinate speaker sessions, exhibitors, and attendee experiences. Oversee event registration and marketing.",Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & Gas Exploration & Production"",""City"":""Edinburgh"",""State"":""Scotland"",""Zip"":""EH2 4NH"",""Website"":""https://www.cairnenergy.com/"",""Ticker"":""CNE"",""CEO"":""Sim..."

## Basic Inspection

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  str
 2   Qualifications    1615940 non-null  str
 3   Salary Range      1615940 non-null  str
 4   location          1615940 non-null  str
 5   Country           1615940 non-null  str
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  str
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  str
 11  Preference        1615940 non-null  str
 12  Contact Person    1615940 non-null  str
 13  Contact           1615940 non-null  str
 14  Job Title         1615940 non-null  str
 15  Role              1615940 non-null  str
 16  Job Portal        1615940 non-null  str
 17  Job Description   1615940 non-null  str
 18  Benefits          1615940 non-null  str
 19  skills            1615940 non-null  str
 20  Responsibilities  1615940 non-null  str
 21  Company           1615940 non-null  str
 22  Company Profile   1610462 non-null  str
dtypes: float64(2), int64(2), str(19)
memory usage: 283.6 MB

In [5]:
df.isnull().sum()

Job Id                 0
Experience             0
Qualifications         0
Salary Range           0
location               0
Country                0
latitude               0
longitude              0
Work Type              0
Company Size           0
Job Posting Date       0
Preference             0
Contact Person         0
Contact                0
Job Title              0
Role                   0
Job Portal             0
Job Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company Profile     5478
dtype: int64

In [6]:
df.describe(include="object")

C:\Users\USER\AppData\Local\Temp\ipykernel_5584\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Experience,Qualifications,Salary Range,location,Country,Work Type,Job Posting Date,Preference,Contact Person,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
count,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1615940,1610462
unique,48,10,561,214,216,5,731,3,367128,1615933,147,376,16,376,11,376,375,888,884
top,5 to 8 Years,BBA,$59K-$88K,Seoul,Malta,Part-Time,2021-11-14,Male,Michael Smith,+1-507-963-5920,UX/UI Designer,Interaction Designer,FlexJobs,Interaction Designers specialize in designing user interactions within digital interfaces. They create meaningful and engaging user experiences by considering user behaviors and system responses.,"{'Childcare Assistance, Paid Time Off (PTO), Relocation Assistance, Flexible Work Arrangements, Professional Development'}",Interaction design principles User behavior and psychology Wireframing and prototyping tools Animation and micro-interaction design Collaborative design processes,"Work on interaction design, defining how users interact with digital products and ensuring a seamless user journey. Create wireframes and prototypes to illustrate interactions. Collaborate with de...",DTE Energy,"{""Sector"":""Automotive"",""Industry"":""Automotive"",""City"":""Munich"",""State"":""N/A"",""Zip"":""N/A"",""Website"":""www.bmwgroup.com"",""Ticker"":""BMW"",""CEO"":""Oliver Zipse""}"
freq,34120,162148,3043,15104,7723,324044,2378,539167,838,2,48551,20580,129879,20580,161924,20580,20580,1957,3572

## Select relevant columns

In [7]:
# Example column names
df = df[["Job Title", "Job Description"]]

df.head()

,Job Title,Job Description
0,Digital Marketing Specialist,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagem..."
1,Web Developer,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create ..."
2,Operations Manager,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain p..."
3,Network Engineer,"Wireless Network Engineers design, implement, and maintain wireless network solutions. They optimize wireless connectivity, troubleshoot issues, and ensure reliable and secure wireless communicati..."
4,Event Manager,"A Conference Manager coordinates and manages conferences, meetings, and events. They plan logistics, handle budgeting, liaise with vendors, and ensure the smooth execution of events, catering to t..."

## Drop Missing & Duplicates

In [8]:
# Remove missing
df.dropna(subset=["Job Title", "Job Description"], inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("After cleaning shape:", df.shape)

After cleaning shape: (376, 2)

## Text Cleaning Function

In [9]:
def clean_text(text):
    # Lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r"http\S+", "", text)
    
    # Remove numbers
    text = re.sub(r"\d+", "", text)
    
    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [10]:
df["clean_title"] = df["Job Title"].apply(clean_text)
df["clean_description"] = df["Job Description"].apply(clean_text)

df.head()

,Job Title,Job Description,clean_title,clean_description
0,Digital Marketing Specialist,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagem...",digital marketing specialist,social media managers oversee an organizations social media presence they create and schedule content engage with followers and analyze social media metrics to drive brand awareness and engagement
1,Web Developer,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create ...",web developer,frontend web developers design and implement user interfaces for websites ensuring they are visually appealing and userfriendly they collaborate with designers and backend developers to create sea...
2,Operations Manager,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain p...",operations manager,quality control managers establish and enforce quality standards within an organization they develop quality control processes perform inspections and implement corrective actions to maintain prod...
3,Network Engineer,"Wireless Network Engineers design, implement, and maintain wireless network solutions. They optimize wireless connectivity, troubleshoot issues, and ensure reliable and secure wireless communicati...",network engineer,wireless network engineers design implement and maintain wireless network solutions they optimize wireless connectivity troubleshoot issues and ensure reliable and secure wireless communications
4,Event Manager,"A Conference Manager coordinates and manages conferences, meetings, and events. They plan logistics, handle budgeting, liaise with vendors, and ensure the smooth execution of events, catering to t...",event manager,a conference manager coordinates and manages conferences meetings and events they plan logistics handle budgeting liaise with vendors and ensure the smooth execution of events catering to the need...

## Combine Text Fields

In [11]:
df["text"] = df["clean_title"] + " " + df["clean_description"]

## Basic Text Analysis

### Average description length

In [12]:
df["text_length"] = df["text"].apply(lambda x: len(x.split()))

df["text_length"].describe()

count    376.000000
mean      26.361702
std        7.524327
min       12.000000
25%       22.000000
50%       26.000000
75%       30.000000
max       64.000000
Name: text_length, dtype: float64

## Top 20 most common words

In [13]:
from collections import Counter

all_words = " ".join(df["text"]).split()
word_counts = Counter(all_words)

word_counts.most_common(20)

[('and', 839),
 ('to', 289),
 ('they', 219),
 ('a', 140),
 ('the', 123),
 ('in', 114),
 ('with', 102),
 ('data', 86),
 ('for', 75),
 ('ensure', 73),
 ('of', 72),
 ('manager', 71),
 ('on', 69),
 ('marketing', 66),
 ('or', 57),
 ('support', 57),
 ('financial', 55),
 ('develop', 54),
 ('provide', 54),
 ('sales', 52)]

## Final Dataset Selection

We now keep only necessary columns for ML.

In [14]:
df.rename(columns={
    "Job Title": "title",
    "Job Description": "description"
}, inplace=True)

final_df = df[["title", "description", "text"]].copy()

print(final_df.shape)
final_df.head()

(376, 3)

,title,description,text
0,Digital Marketing Specialist,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagem...",digital marketing specialist social media managers oversee an organizations social media presence they create and schedule content engage with followers and analyze social media metrics to drive b...
1,Web Developer,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create ...",web developer frontend web developers design and implement user interfaces for websites ensuring they are visually appealing and userfriendly they collaborate with designers and backend developers...
2,Operations Manager,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain p...",operations manager quality control managers establish and enforce quality standards within an organization they develop quality control processes perform inspections and implement corrective actio...
3,Network Engineer,"Wireless Network Engineers design, implement, and maintain wireless network solutions. They optimize wireless connectivity, troubleshoot issues, and ensure reliable and secure wireless communicati...",network engineer wireless network engineers design implement and maintain wireless network solutions they optimize wireless connectivity troubleshoot issues and ensure reliable and secure wireless...
4,Event Manager,"A Conference Manager coordinates and manages conferences, meetings, and events. They plan logistics, handle budgeting, liaise with vendors, and ensure the smooth execution of events, catering to t...",event manager a conference manager coordinates and manages conferences meetings and events they plan logistics handle budgeting liaise with vendors and ensure the smooth execution of events cateri...

## Save Processed Dataset

In [15]:
final_df.to_csv("../data/processed/job_postings_cleaned.csv", index=False)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.